# Generated by Django 4.1.7 on 2023-04-18 09:04

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vtuber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('Ddate', models.DateField(null=True)),
                ('slug', models.SlugField(max_length=128, null=True, unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('content', models.TextField(null=True)),
                ('infoo', models.TextField(null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
